version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8001:8000
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=microdb1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ROOT
    ports:
      - 5433:5432
    volumes:
        - ./data:/var/lib/postgresql/data




