from collections import deque
q=deque()
q.append(10)
q.append(20)
q.append(30)
q.append(40)
q.append(50)
q.append(60)
print("Elmns in the queue are ")
print(q)
print(q.popleft())
print(q.popleft())
print(q.popleft())
print(q)
